
-- Continuous Innovation & Expansion Generator tables

-- 1. Innovation proposals generated by AI or operators
CREATE TABLE public.inn_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  overview TEXT,
  core_components JSONB DEFAULT '[]',
  architecture_design JSONB DEFAULT '{}',
  data_model JSONB DEFAULT '{}',
  integration_points JSONB DEFAULT '[]',
  revenue_model JSONB DEFAULT '{}',
  expected_impact JSONB DEFAULT '{}',
  innovation_score NUMERIC DEFAULT 0,
  revenue_potential NUMERIC DEFAULT 0,
  complexity TEXT DEFAULT 'medium',
  status TEXT DEFAULT 'proposed',
  created_by UUID,
  reviewed_by UUID,
  reviewed_at TIMESTAMPTZ,
  review_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_inn_proposals_status ON public.inn_proposals(status);
CREATE INDEX idx_inn_proposals_category ON public.inn_proposals(category);

ALTER TABLE public.inn_proposals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Auth read inn_proposals" ON public.inn_proposals FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert inn_proposals" ON public.inn_proposals FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update inn_proposals" ON public.inn_proposals FOR UPDATE TO authenticated USING (true);

-- 2. Impact projections for proposals
CREATE TABLE public.inn_impact_projections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id UUID REFERENCES public.inn_proposals(id) ON DELETE CASCADE,
  projection_type TEXT NOT NULL,
  time_horizon TEXT NOT NULL,
  projected_revenue NUMERIC DEFAULT 0,
  projected_users INTEGER DEFAULT 0,
  projected_institutions INTEGER DEFAULT 0,
  confidence_score NUMERIC DEFAULT 0,
  assumptions JSONB DEFAULT '[]',
  risks JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.inn_impact_projections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Auth read inn_impact" ON public.inn_impact_projections FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert inn_impact" ON public.inn_impact_projections FOR INSERT TO authenticated WITH CHECK (true);

-- 3. Expansion roadmap items
CREATE TABLE public.inn_roadmap (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id UUID REFERENCES public.inn_proposals(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  phase TEXT NOT NULL,
  priority TEXT DEFAULT 'medium',
  estimated_effort TEXT,
  dependencies TEXT[] DEFAULT '{}',
  target_quarter TEXT,
  status TEXT DEFAULT 'planned',
  progress NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.inn_roadmap ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Auth read inn_roadmap" ON public.inn_roadmap FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert inn_roadmap" ON public.inn_roadmap FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update inn_roadmap" ON public.inn_roadmap FOR UPDATE TO authenticated USING (true);

-- 4. Innovation metrics tracking
CREATE TABLE public.inn_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_name TEXT NOT NULL,
  metric_value NUMERIC DEFAULT 0,
  metric_type TEXT NOT NULL,
  period TEXT NOT NULL,
  category TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.inn_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Auth read inn_metrics" ON public.inn_metrics FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert inn_metrics" ON public.inn_metrics FOR INSERT TO authenticated WITH CHECK (true);
